### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by ghost** [netweak/agent#1]
As of June, I now have a Mac server and was interested in adding this to my Netweak dashboard.
However, I seem to be having issues with the agent script.

![image](https://github.com/netweak/agent/assets/51213244/275d6d55-9289-49e1-907b-5db9b96eaf78)

**Comment by lucasdcrk** [comment]
Hi,
I’ll take a look on this next week!

**Comment by ghost** [comment]
Alright thanks, while you are at it, you could take a look and see if Windows support is 
there as well. Optionally, people would just use WSL instead to use this on Windows.

## Temporary Solution
SudoVanilla has a Docker Image available for the Netweak Agent that customers may use on their servers that are running either Windows or macOS.

| Source           | Arch  | Image                                              |
|------------------|-------|----------------------------------------------------|
| SudoVanilla Ark  | ARM64 | `ark.sudovanilla.org/korbs/netweak-agent:arm64`    | 
| SudoVanilla Ark  | AMD64 |  `ark.sudovanilla.org/korbs/netweak-agent:amd64`

Source Code: https://ark.sudovanilla.org/Korbs/Netweak-Agent-Docker
