### ISSUE TITLE
Replacing wget by curl in installation process

### ISSUE THREAD

**Issue by payagej** [netweak/agent#2]
Hello there, 

On some linux distribution, `wget` isn't available by default, unlike `curl` which is installed on every system, wouldn't it be better to download the agent using curl?

Replacing on [L122](https://github.com/netweak/agent/blob/master/install.sh#L122C1-L122C189):
`echo -e "|   Downloading agent.sh to /etc/netweak\n|\n|   + $(wget -nv -o /dev/stdout -O /etc/netweak/agent.sh --no-check-certificate https://github.com/netweak/agent/raw/master/agent.sh)"`

by:
`echo -e "|   Downloading agent.sh to /etc/netweak\n|\n|   + $(curl -JLso /etc/netweak/agent.sh https://github.com/netweak/agent/raw/master/agent.sh)"`

**Comment by lucasdcrk** [comment]
Thanks btw!
